#!/bin/sh

echo "Cleaning..."

rm ./builds/* -rf

echo "Done."

VERSION="2.6.$(git rev-list --all --count)"
DPKG="imd_$VERSION-1_any"

echo "Packing IMD version $VERSION."

cd builds

echo "Building Arch Binaries..."

cat <<EOF > ./PKGBUILD
pkgbase="imd"
pkgname="imd"
pkgver=$VERSION
pkgrel=1
pkgdesc="Improved MarkDown Reader"

arch=("any")

makedepends=("python3" "git" "gzip")
depends=("glibc" "binutils" "make" "gcc")

license=("MIT")

url="https://github.com/Noah-Arcouette/imd.git"

provides=("imd")
conflicts=("imd")

giturl="https://raw.githubusercontent.com/Noah-Arcouette/imd/master/"

source=(
	"git+\${url}"
)

sha256sums=(
	"SKIP"
)


pkgver () {
	cd "imd"
	printf "2.6.%s" "\$(git rev-list --count --all)"
}

build () {
	cd "imd"

	make clean

	make -j 1 build
}

package() {
	cd "imd"

	# setup dirs
	mkdir -p "\${pkgdir}/usr/bin/"
	mkdir -p "\${pkgdir}/etc/imd/"
	mkdir -p "\${pkgdir}/etc/imd/src/"
	mkdir -p "\${pkgdir}/usr/share/man/man1/"

	# make binary root owned and executable
	chown root:root \${srcdir}/imd/bin/imd
	chmod a+x \${srcdir}/imd/bin/imd

	# copy docs
	cp "\${srcdir}/imd/doc/man.md" "\${pkgdir}/etc/imd/man.md"
	cp "\${srcdir}/imd/imd.1.gz" "\${pkgdir}/usr/share/man/man1/imd.1.gz"

	# copy sources
	cp \${srcdir}/imd/src/* "\${pkgdir}/etc/imd/src/"
	cp \${srcdir}/imd/inc/* "\${pkgdir}/etc/imd/src/"
	cp "\${srcdir}/imd/LICENSE.TXT" "\${pkgdir}/etc/imd/"

	cp "\${srcdir}/imd/rebuild/makefile" "\${pkgdir}/etc/imd/"

	# copy binary
	mv "\${srcdir}/imd/bin/imd" "\${pkgdir}/usr/bin/imd"
	mv "\${srcdir}/imd/rebuild/imd-rebuild" "\${pkgdir}/usr/bin/imd-rebuild"
}

EOF

makepkg --clean --force

echo "Done."

echo "Building Debian Binaries..."

echo "Make Dirs."

mkdir -p ./$DPKG/usr/bin/
mkdir -p ./$DPKG/etc/imd/src/
mkdir -p ./$DPKG/usr/share/man/man1/
mkdir -p ./$DPKG/DEBIAN

echo "Copying Manuals."

cp ../doc/man.md ./$DPKG/etc/imd/man.md
cp ../imd.1.gz ./$DPKG/usr/share/man/man1/imd.1.gz

echo "Copying rebuilds."

cp ../src/* ./$DPKG/etc/imd/src/
cp ../inc/* ./$DPKG/etc/imd/src/
cp ../LICENSE.TXT ./$DPKG/etc/imd/LICENSE.TXT
cp ../rebuild/makefile ./$DPKG/etc/imd/

cp ../rebuild/imd-rebuild ./$DPKG/usr/bin/imd-rebuild
chmod a+x ./$DPKG/usr/bin/imd-rebuild

echo "Copying IMD."

cp ../bin/imd ./$DPKG/usr/bin/imd
chmod a+x ./$DPKG/usr/bin/imd

echo "Making control file."

cat <<EOF > ./$DPKG/DEBIAN/control
Package: imd
Version: $VERSION
Architecture: any
Maintainer: Noah Arcouette
Description: Improved Markdown Reader
Depends: gcc, make, binutils
Conflicts: imd
Section: base

EOF

echo "Building .deb..."

dpkg-deb --build --root-owner-group ./$DPKG/

echo "Done."
