#!/bin/sh
REVS=$(git rev-list --all --count)

printf "#ifndef __IMD_VERSION_INFO__\n\
#define __IMD_VERSION_INFO__\n\
# define IMD_VERSION \"$1\"\n\
# define IMD_REVS \"$REVS\"\n\
#endif\n\
" > ./inc/vinfo.h
