.TH IMD 1 "May 2022" GNU

.SH NAME
imd \- Improved MarkDown Reader

.SH SYNOPSIS
.B IMD
\fIfile\fR
[\fBoptions\fR]

.SH DESCRIPTION
.B MD
Display a stylized version of a MarkDown file

.SH OPTIONS
.TP
.BR \fIfile\fR
File to read and style.

.TP
.BR \-h,\-\-help
Display help info.

.TP
.BR \-r,\-\-raw
Print data without pager.

.TP
.BR \-d,\-\-no\-decoration
No decoration I.E line numbers and file name.

.TP
.BR \-s,\-\-no\-syntax
No syntax highlighting.

.SH KEYBINDINGS

.TP
.BR w-s
Up-Down

.TP
.BR j-k
Up-Down

.TP
.BR ArrowUp-ArrowDown
Up-Down

.TP
.BR PageUp-PageDown
PagedUp-PagedDown

.TP
.BR Mouse Wheel
Just scroll

.TP
.BR q
Quit.
